/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * euchreTest.java
 *
 * Created on Mar 21, 2010, 6:00:10 PM
 */

package com.useric.euchre;

/**
 *
 * @author Eric
 */
public class euchreTest extends java.awt.Frame {

    /** Creates new form euchreTest */
    public euchreTest() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        player2 = new java.awt.Panel();
        player3 = new java.awt.Panel();
        player1 = new java.awt.Panel();
        player0 = new java.awt.Panel();
        playtable = new java.awt.Panel();
        info = new java.awt.Panel();
        label5 = new java.awt.Label();
        label4 = new java.awt.Label();
        label6 = new java.awt.Label();
        panel2 = new java.awt.Panel();
        label1 = new java.awt.Label();
        panel3 = new java.awt.Panel();
        label3 = new java.awt.Label();
        panel4 = new java.awt.Panel();
        label2 = new java.awt.Label();
        panel5 = new java.awt.Panel();
        panel6 = new java.awt.Panel();
        panel7 = new java.awt.Panel();
        panel8 = new java.awt.Panel();
        panel9 = new java.awt.Panel();
        panel10 = new java.awt.Panel();
        panel12 = new java.awt.Panel();
        panel13 = new java.awt.Panel();
        panel14 = new java.awt.Panel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(51, 153, 0));
        panel1.setLayout(new java.awt.BorderLayout());

        player2.setLayout(new javax.swing.BoxLayout(player2, javax.swing.BoxLayout.X_AXIS));
        panel1.add(player2, java.awt.BorderLayout.NORTH);
        player2.getAccessibleContext().setAccessibleName("player2");

        player3.setLayout(new javax.swing.BoxLayout(player3, javax.swing.BoxLayout.Y_AXIS));
        panel1.add(player3, java.awt.BorderLayout.EAST);
        player3.getAccessibleContext().setAccessibleName("player3");

        player1.setLayout(new javax.swing.BoxLayout(player1, javax.swing.BoxLayout.Y_AXIS));
        panel1.add(player1, java.awt.BorderLayout.WEST);
        player1.getAccessibleContext().setAccessibleName("player1");

        player0.setLayout(new javax.swing.BoxLayout(player0, javax.swing.BoxLayout.X_AXIS));
        panel1.add(player0, java.awt.BorderLayout.SOUTH);
        player0.getAccessibleContext().setAccessibleName("player0");

        playtable.setBackground(new java.awt.Color(0, 153, 0));
        playtable.setLayout(new java.awt.BorderLayout());

        info.setBackground(new java.awt.Color(0, 153, 0));
        info.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        label5.setName("score"); // NOI18N
        label5.setText("Score - Team NS:  ; Team EW:  ;");
        info.add(label5);

        label4.setText(" ");
        info.add(label4);
        label4.getAccessibleContext().setAccessibleName("null");

        label6.setName("tricks"); // NOI18N
        label6.setText("Tricks - Team NS:  ; Team EW:  ;");
        info.add(label6);

        playtable.add(info, java.awt.BorderLayout.NORTH);
        info.getAccessibleContext().setAccessibleName("info");

        panel2.setBackground(new java.awt.Color(0, 153, 0));

        label1.setText("          ");
        panel2.add(label1);

        playtable.add(panel2, java.awt.BorderLayout.WEST);

        panel3.setBackground(new java.awt.Color(0, 153, 0));

        label3.setText(" ");
        panel3.add(label3);

        playtable.add(panel3, java.awt.BorderLayout.SOUTH);

        panel4.setBackground(new java.awt.Color(0, 153, 0));

        label2.setText("          ");
        panel4.add(label2);

        playtable.add(panel4, java.awt.BorderLayout.EAST);

        panel5.setBackground(new java.awt.Color(0, 153, 0));
        panel5.setLayout(new java.awt.BorderLayout());

        panel7.setBackground(new java.awt.Color(0, 0, 0));
        panel6.add(panel7);

        panel5.add(panel6, java.awt.BorderLayout.NORTH);

        panel9.setBackground(new java.awt.Color(0, 0, 0));
        panel8.add(panel9);

        panel5.add(panel8, java.awt.BorderLayout.SOUTH);

        panel12.setBackground(new java.awt.Color(0, 0, 0));
        panel10.add(panel12);

        panel13.setBackground(new java.awt.Color(0, 0, 0));
        panel10.add(panel13);

        panel14.setBackground(new java.awt.Color(0, 0, 0));
        panel10.add(panel14);

        panel5.add(panel10, java.awt.BorderLayout.CENTER);

        playtable.add(panel5, java.awt.BorderLayout.CENTER);

        panel1.add(playtable, java.awt.BorderLayout.CENTER);
        playtable.getAccessibleContext().setAccessibleName("playtable");

        add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new euchreTest().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel info;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Panel panel1;
    private java.awt.Panel panel10;
    private java.awt.Panel panel12;
    private java.awt.Panel panel13;
    private java.awt.Panel panel14;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    private java.awt.Panel panel7;
    private java.awt.Panel panel8;
    private java.awt.Panel panel9;
    private java.awt.Panel player0;
    private java.awt.Panel player1;
    private java.awt.Panel player2;
    private java.awt.Panel player3;
    private java.awt.Panel playtable;
    // End of variables declaration//GEN-END:variables

}
